### ISSUE TITLE
Create CI for instrumental tests (UI)

### ISSUE THREAD

**Issue by Canato** [Canato/Purity-Test#55]
Check https://github.com/marketplace/actions/android-emulator-runner

```
name: UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew <UI Test command>
```
